spring:
  application:
    name: Welcome-API-Client-2

#admin server url --this will register our hello api /welcom2 api with admin server as a client

  boot:
    admin:
      client:
        url: http://localhost:4444/

server:
 port: 2222
 
 #enable the actuator endpoint

management:
  endpoints:
   web:
    exposure:
     include: '*'
